# Generated by Django 3.0.2 on 2020-01-23 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deliverable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(default='', null=True)),
                ('release_date', models.DateField(auto_now=True, null=True)),
                ('pipeline', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('template', models.FileField(blank=True, null=True, upload_to='deliverables/')),
                ('icon', models.CharField(blank=True, default='group', max_length=100, null=True)),
                ('deadline', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Helpfullink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=255, null=True)),
                ('course_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RealTeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('role', models.CharField(max_length=100, null=True)),
                ('team_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('pipeline', models.CharField(max_length=100, null=True)),
                ('research_stream', models.BooleanField(default=False, null=True)),
                ('maturity_level', models.IntegerField(null=True)),
                ('date_of_entry', models.DateField(auto_now=True, null=True)),
                ('website', models.CharField(blank=True, max_length=100, null=True)),
                ('coorporate_existance', models.BooleanField(default=False, null=True)),
                ('tag_line', models.CharField(blank=True, max_length=100, null=True)),
                ('about', models.TextField(blank=True, default='', max_length=1000, null=True)),
                ('coach_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('is_coach', models.BooleanField(default=False)),
                ('is_team_member', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vap.User')),
                ('job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('organization', models.CharField(blank=True, max_length=100, null=True)),
                ('field', models.CharField(blank=True, max_length=100, null=True)),
                ('about_me', models.TextField(blank=True, default='', null=True)),
                ('photo', models.ImageField(blank=True, max_length=200, null=True, upload_to='img/')),
            ],
            bases=('vap.user',),
        ),
        migrations.CreateModel(
            name='TeamDeliverable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateField(blank=True, null=True)),
                ('status', models.BooleanField(default=False, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='teamdeliverables/')),
                ('deliverable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverable', to='vap.Deliverable')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vap.Team')),
            ],
            options={
                'unique_together': {('deliverable', 'team')},
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vap.User')),
                ('role', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('field', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vap.Team')),
            ],
            bases=('vap.user',),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='', null=True)),
                ('date', models.DateField(auto_now=True, null=True)),
                ('teamdeliverable', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='vap.TeamDeliverable')),
                ('coach', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vap.Coach')),
            ],
        ),
    ]
