# Generated by Django 3.0.2 on 2020-01-28 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverable',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliverable',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
