# Generated by Django 3.0.2 on 2020-01-28 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vap', '0002_auto_20200129_0605'),
    ]

    operations = [
        migrations.AddField(
            model_name='realteammember',
            name='role1',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
