# Generated by Django 3.0.2 on 2020-01-29 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vap', '0004_remove_realteammember_role1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='photo',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
