# Generated by Django 3.0.2 on 2020-01-29 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vap', '0005_auto_20200130_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='photo',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
