# Generated by Django 3.0.2 on 2020-01-30 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vap', '0006_auto_20200130_0437'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='login_date_1st',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='deliverable',
            name='deadline',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliverable',
            name='release_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
