# Generated by Django 3.0.2 on 2020-02-04 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vap', '0007_auto_20200131_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='coach_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='date_of_entry',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='maturity_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='pipeline',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='research_stream',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
